# Generated by Django 5.0.6 on 2024-05-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_project_image_alter_project_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Projekt", "verbose_name_plural": "Projekty"},
        ),
        migrations.AddField(
            model_name="project",
            name="mycode",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL mého projektu."
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="popisek"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="static/", verbose_name="Obrázek"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=100, verbose_name="jméno"),
        ),
    ]
