# Generated by Django 5.0.6 on 2024-05-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_alter_project_options_project_mycode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Čas vytvoření:"
            ),
        ),
    ]
