# Generated by Django 5.0.6 on 2024-05-22 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_project_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeProject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Jméno:")),
                (
                    "description",
                    models.TextField(max_length=100, verbose_name="Popisek:"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Čas vytvoření:"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.typeproject",
            ),
            preserve_default=False,
        ),
    ]
