# Generated by Django 5.0.6 on 2024-05-24 06:43

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "portfolio",
            "0007_typeurl_alter_typeproject_options_alter_project_typ_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Jméno")),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FF00000",
                        image_field=None,
                        max_length=100,
                        samples=None,
                        verbose_name="Barva:",
                    ),
                ),
            ],
            options={
                "verbose_name": "TAG",
                "verbose_name_plural": "TAGY",
            },
        ),
    ]
