# Generated by Django 5.0.6 on 2024-05-24 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0008_typetag"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tagy",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="project",
                to="portfolio.typeurl",
                verbose_name="Tagy",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="typ_sluzby_projektu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="portfolio.typetag",
            ),
        ),
    ]
