# Generated by Django 5.0.6 on 2024-05-24 08:02

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_project_tagy_alter_project_typ_sluzby_projektu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=markdownx.models.MarkdownxField(
                blank=True, max_length=1000, null=True, verbose_name="popisek"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tagy",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="aaa",
                to="portfolio.typetag",
                verbose_name="Tagy",
            ),
        ),
    ]
